### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by roar-emaus** [roar-emaus/metno_gifs_cpp#2]
- [ ] butterflow to interpolate between images? (increase framerate)
- [ ] fix colormaps (find a way to make ranges more global)
- [ ] radiation needs to be de accumulated
